# Generated by Django 5.2.7 on 2025-10-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
