# Generated by Django 5.2.8 on 2025-11-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=30)),
                ('followers', models.CharField(max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=20)),
                ('DOB', models.DateField()),
                ('profile_pic', models.URLField(default='Empty')),
            ],
        ),
    ]
