# Generated by Django 5.2.7 on 2025-10-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('profile_picture', models.FileField(upload_to='profiles/')),
            ],
        ),
    ]
