# Generated by Django 5.2.7 on 2025-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
