# Generated by Django 5.2.7 on 2025-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='profile_pic',
            field=models.URLField(default=None),
        ),
    ]
