# Generated by Django 5.2.7 on 2025-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_instagram_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='profile_pic',
            field=models.URLField(blank=True, default='empty', null=True),
        ),
    ]
