# Generated by Django 5.2.7 on 2025-10-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_branch', models.CharField(max_length=20)),
                ('stu_ph', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
